In [1]:
! python main.py --data_path='/home/youngjoon/Desktop/ntu_gen_real_npy/' --n_epochs=1

Number of GPUs available: 1
Total Video Samples: 1198 || Total Participants: 104 || Train Participants: 84 || Validation Participants: 20
Train samples: 3117 || Validation samples: 477
Training...
100%|████████████████████████████████████████| 390/390 [00:02<00:00, 170.97it/s]
Epoch: 0 | Loss: 2.2969841957092285
Testing...
100%|████████████████████████████████████████| 390/390 [00:01<00:00, 276.14it/s]
Model accuracy: 43.471286493423165
[[143   0   0   0   0   0   2   0  72   0   1   0  13]
 [  1  84   0   0   5  22   0  78   4  16  32   0  10]
 [ 21   0  74   0   0   0   4   1  73   3  20   5   6]
 [ 18   0   5   3   0   0  15   4  85   2  68  20  23]
 [  0   7   0   0 231   8   0   6   0   3   0   0   0]
 [  3   0   7   0  36  85   0  56   8  24  20   0   4]
 [  0  16   3   0   0   2  66   2  43   1 101   6  27]
 [  0   0   3   0   0  19   0 153   3  15  44   0   0]
 [  9   0   3   0   0   0   1   0 201   0  26   0  12]
 [  0   0   0   0   0  30   0 105  12  27  42   0   0]
 [  0   0

In [2]:
! python main.py --data_path='/home/youngjoon/Desktop/ntu_raw_npy/' --n_epochs=1

Number of GPUs available: 1
Total Video Samples: 1191 || Total Participants: 104 || Train Participants: 84 || Validation Participants: 20
Train samples: 2982 || Validation samples: 591
Training...
100%|████████████████████████████████████████| 373/373 [00:03<00:00, 113.52it/s]
Epoch: 0 | Loss: 0.9217536449432373
Testing...
100%|████████████████████████████████████████| 373/373 [00:02<00:00, 137.60it/s]
Model accuracy: 55.60026827632461
[[ 86   3  17  43   0   5   5   0  55   0   4   3  10]
 [  7 107   3   0  15  20   0  19   0  11  15  28  12]
 [  0   0 190   2   0   6   3   0   6   0   0   0   0]
 [  3   0   3 174   0   3   3   0  36   0   3   3   6]
 [  0   6   3   0 219   0   0   3   0   0   0   0   0]
 [  0   3  12   4  36 105   0   9   6  45   8   0   0]
 [  8   0   6  53   0   0  91   0  10   0   5  49  18]
 [  0  41   0   0   9  27   0  68   0  65  25   2   0]
 [  6   0   6   9   0   3   9   0 189   0   6   3  12]
 [  0  12  12   0   9  11   0  18   0 103  33   9   3]
 [  7  18 

In [1]:
!python main.py --data_path='/home/youngjoon/Desktop/Dataset/humanact12/' --n_epochs=1000

Number of GPUs available: 1
Total Video Samples: 1191 || Total Participants: 12 || Train Participants: 10 || Validation Participants: 2
Train samples: 4825 || Validation samples: 1130
Training...
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
Epoch: 0 | Loss: 3.5463614463806152
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.92it/s]
Epoch: 1 | Loss: 3.5101213455200195
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.91it/s]
Epoch: 2 | Loss: 3.3986825942993164
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
Epoch: 3 | Loss: 3.4061691761016846
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
Epoch: 4 | Loss: 3.2791531085968018
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.89it/s]
Epoch: 5 | Loss: 3.151402711868286
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.89it/s]
Epoch: 6 | Loss: 2.916

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 68 | Loss: 0.06663066893815994
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 69 | Loss: 0.046728603541851044
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 70 | Loss: 0.051533035933971405
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 71 | Loss: 0.039195261895656586
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 72 | Loss: 0.04303690046072006
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 73 | Loss: 0.03760217875242233
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 74 | Loss: 0.062446340918540955
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 75 | Loss: 0.03450385481119156
100%|███████████████████████████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.84it/s]
Epoch: 203 | Loss: 0.004553060047328472
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 204 | Loss: 0.0017091694753617048
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 205 | Loss: 0.0018216307507827878
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 206 | Loss: 0.005292259622365236
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 207 | Loss: 0.003114929888397455
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 208 | Loss: 0.0008476364309899509
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 209 | Loss: 0.0017184417229145765
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 210 | Loss: 0.0004735071852337569
100%|██████████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 337 | Loss: 0.005578754004091024
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 338 | Loss: 0.21546925604343414
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 339 | Loss: 0.026694005355238914
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 340 | Loss: 0.0076643554493784904
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 341 | Loss: 0.002464478136971593
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 342 | Loss: 0.0008848294382914901
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 343 | Loss: 0.0005911202752031386
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 344 | Loss: 0.0015867366455495358
100%|████████████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 471 | Loss: 9.779872198123485e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 472 | Loss: 0.0001284559111809358
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 473 | Loss: 5.8306883147452027e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 474 | Loss: 5.0604852731339633e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 475 | Loss: 3.541147816576995e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 476 | Loss: 0.0003026127815246582
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 477 | Loss: 4.4664273445960134e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 478 | Loss: 6.382134597515687e-05
100%|████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 605 | Loss: 5.7632361858850345e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 606 | Loss: 2.674242205102928e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 607 | Loss: 0.0001331583334831521
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 608 | Loss: 0.00014848464343231171
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 609 | Loss: 4.190954132354818e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 610 | Loss: 3.497386569506489e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 611 | Loss: 2.816662163240835e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 612 | Loss: 3.0059238270041533e-05
100%|████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 739 | Loss: 0.0009661463554948568
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 740 | Loss: 0.0003481860621832311
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 741 | Loss: 9.761962428456172e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 742 | Loss: 9.46153377299197e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 743 | Loss: 0.00012010426871711388
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 744 | Loss: 6.870775541756302e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 745 | Loss: 2.8929101972607896e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 746 | Loss: 0.0001017384129227139
100%|██████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 873 | Loss: 1.190637249237625e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 874 | Loss: 1.5499948858632706e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 875 | Loss: 1.1076269402110483e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 876 | Loss: 1.4789216038479935e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 877 | Loss: 8.068192073551472e-06
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 878 | Loss: 1.7070180547307245e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 879 | Loss: 9.07460616872413e-06
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 880 | Loss: 8.985572094388772e-06
100%|████████████████

In [3]:
!python main.py --data_path='/home/youngjoon/Desktop/Dataset/humanact12/' --n_epochs=200

Number of GPUs available: 1
Total Video Samples: 1191 || Total Participants: 12 || Train Participants: 10 || Validation Participants: 2
Train samples: 5095 || Validation samples: 860
Training...
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.87it/s]
Epoch: 0 | Loss: 3.5243964195251465
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.87it/s]
Epoch: 1 | Loss: 3.47042179107666
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 2 | Loss: 3.3230433464050293
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 3 | Loss: 3.0652105808258057
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 4 | Loss: 2.9054062366485596
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 5 | Loss: 2.5773046016693115
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 6 | Loss: 2.55123

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 134 | Loss: 7.980904774740338e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 135 | Loss: 0.0002882445405703038
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 136 | Loss: 6.873581151012331e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 137 | Loss: 6.634956662310287e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 138 | Loss: 7.882650970714167e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 139 | Loss: 6.666148692602292e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 140 | Loss: 0.0004781275929417461
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 141 | Loss: 0.00015732931206002831
100%|██████████████████

100%|█████████████████████████████████████████████| 2/2 [00:00<00:00,  3.84it/s]
Model accuracy: 70.0
[[20  0  0 ...  0  0  0]
 [ 0 40  0 ...  0  0  0]
 [ 0  0 25 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0 15  0]
 [ 0  0  0 ...  0  0  0]]


In [4]:
!python main.py --data_path='/home/youngjoon/Desktop/Dataset/humanact12/' --n_epochs=300

Number of GPUs available: 1
Total Video Samples: 1191 || Total Participants: 12 || Train Participants: 10 || Validation Participants: 2
Train samples: 4765 || Validation samples: 1190
Training...
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
Epoch: 0 | Loss: 3.540884494781494
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.91it/s]
Epoch: 1 | Loss: 3.5128796100616455
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
Epoch: 2 | Loss: 3.3935887813568115
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.91it/s]
Epoch: 3 | Loss: 3.4922428131103516
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
Epoch: 4 | Loss: 3.532613754272461
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
Epoch: 5 | Loss: 3.4649689197540283
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
Epoch: 6 | Loss: 3.5207

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 68 | Loss: 0.004881607834249735
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 69 | Loss: 0.008047848008573055
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 70 | Loss: 0.004639443941414356
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 71 | Loss: 0.006931923795491457
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 72 | Loss: 0.0007916525937616825
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 73 | Loss: 0.0038500241935253143
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 74 | Loss: 0.0012227928964421153
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 75 | Loss: 0.0007710083154961467
100%|███████████████████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 202 | Loss: 4.614075805875473e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 203 | Loss: 5.4004085541237146e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 204 | Loss: 3.090080281253904e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 205 | Loss: 3.711055251187645e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 206 | Loss: 3.836737960227765e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 207 | Loss: 4.3237207137281075e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 208 | Loss: 4.554611223284155e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 209 | Loss: 0.012869499623775482
100%|██████████████████

In [5]:
!python main.py --data_path='/home/youngjoon/Desktop/Dataset/humanact12/' --n_epochs=400

Number of GPUs available: 1
Total Video Samples: 1191 || Total Participants: 12 || Train Participants: 10 || Validation Participants: 2
Train samples: 4840 || Validation samples: 1115
Training...
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 0 | Loss: 3.5512754917144775
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.87it/s]
Epoch: 1 | Loss: 3.4998881816864014
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.88it/s]
Epoch: 2 | Loss: 3.4932525157928467
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.87it/s]
Epoch: 3 | Loss: 3.4948418140411377
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 4 | Loss: 3.417285442352295
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 5 | Loss: 3.3886313438415527
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 6 | Loss: 3.362

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 136 | Loss: 0.06963449716567993
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 137 | Loss: 0.031028661876916885
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 138 | Loss: 0.3352016508579254
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 139 | Loss: 0.10081752389669418
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 140 | Loss: 0.12732122838497162
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 141 | Loss: 0.07152827084064484
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 142 | Loss: 0.01572359725832939
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 143 | Loss: 0.009844737127423286
100%|██████████████████████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 270 | Loss: 0.018197117373347282
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 271 | Loss: 0.006950551178306341
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 272 | Loss: 0.0050598266534507275
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 273 | Loss: 0.0020085261203348637
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 274 | Loss: 0.13970790803432465
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 275 | Loss: 0.0012912311358377337
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 276 | Loss: 0.021325264126062393
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 277 | Loss: 0.009609384462237358
100%|█████████████████████████

In [1]:
!python main.py --data_path='/home/youngjoon/Desktop/Dataset/humanact12/' --n_epochs=500

Number of GPUs available: 1
Total Video Samples: 1191 || Total Participants: 12 || Train Participants: 10 || Validation Participants: 2
Train samples: 5040 || Validation samples: 915
Training...
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.72it/s]
Epoch: 0 | Loss: 3.5479416847229004
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.74it/s]
Epoch: 1 | Loss: 3.461113214492798
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.71it/s]
Epoch: 2 | Loss: 3.435382604598999
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.72it/s]
Epoch: 3 | Loss: 3.2518367767333984
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.70it/s]
Epoch: 4 | Loss: 3.071439504623413
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.71it/s]
Epoch: 5 | Loss: 3.1086649894714355
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.70it/s]
Epoch: 6 | Loss: 3.062721

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 68 | Loss: 0.044234901666641235
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.69it/s]
Epoch: 69 | Loss: 0.21119120717048645
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 70 | Loss: 0.12812983989715576
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 71 | Loss: 0.33993956446647644
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 72 | Loss: 0.0954693928360939
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 73 | Loss: 0.04054128751158714
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.69it/s]
Epoch: 74 | Loss: 0.03043508715927601
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 75 | Loss: 0.04705415666103363
100%|███████████████████████████████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 136 | Loss: 0.00019733372027985752
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 137 | Loss: 0.00015377526869997382
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 138 | Loss: 9.732591570354998e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 139 | Loss: 0.00010788779036374763
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.69it/s]
Epoch: 140 | Loss: 8.665407949592918e-05
100%|███████████████████████████████████████████| 10/10 [00:06<00:00,  1.66it/s]
Epoch: 141 | Loss: 0.0001447478134650737
100%|███████████████████████████████████████████| 10/10 [00:06<00:00,  1.67it/s]
Epoch: 142 | Loss: 0.00011080321564804763
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 143 | Loss: 8.214266563300043e-05
100%|███████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 270 | Loss: 0.0003893213870469481
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 271 | Loss: 0.0003983503265772015
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 272 | Loss: 0.00012175457959529012
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 273 | Loss: 0.0001322613243246451
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 274 | Loss: 6.939865852473304e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 275 | Loss: 0.0004205023869872093
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 276 | Loss: 6.127787492005154e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 277 | Loss: 8.725794032216072e-05
100%|██████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 404 | Loss: 0.00010688098700484261
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 405 | Loss: 7.252473733387887e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 406 | Loss: 6.64505860186182e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 407 | Loss: 7.077336340444162e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 408 | Loss: 5.7605979236541316e-05
100%|███████████████████████████████████████████| 10/10 [00:06<00:00,  1.66it/s]
Epoch: 409 | Loss: 5.853606489836238e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 410 | Loss: 7.636890950379893e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 411 | Loss: 0.0006575398147106171
100%|██████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 471 | Loss: 2.4971905077109113e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 472 | Loss: 1.7315742297796533e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 473 | Loss: 0.004921413026750088
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 474 | Loss: 0.00015152122068684548
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 475 | Loss: 7.403970812447369e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 476 | Loss: 7.147959695430472e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 477 | Loss: 3.5058103094343096e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 478 | Loss: 2.6053734472952783e-05
100%|███████████████

In [1]:
!python main.py --data_path='/home/youngjoon/Desktop/Dataset/humanact12/' --n_epochs=550

Number of GPUs available: 1
Total Video Samples: 1191 || Total Participants: 12 || Train Participants: 10 || Validation Participants: 2
Train samples: 4780 || Validation samples: 1175
Training...
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 0 | Loss: 3.4465551376342773
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.92it/s]
Epoch: 1 | Loss: 3.3598039150238037
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.92it/s]
Epoch: 2 | Loss: 3.446086883544922
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.81it/s]
Epoch: 3 | Loss: 3.307281255722046
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.89it/s]
Epoch: 4 | Loss: 3.220637083053589
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.84it/s]
Epoch: 5 | Loss: 2.9973442554473877
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.90it/s]
Epoch: 6 | Loss: 3.02693

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.73it/s]
Epoch: 68 | Loss: 0.05659478157758713
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.73it/s]
Epoch: 69 | Loss: 0.010381984524428844
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.73it/s]
Epoch: 70 | Loss: 0.03222275152802467
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 71 | Loss: 0.005455658305436373
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.72it/s]
Epoch: 72 | Loss: 0.0036505674943327904
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.73it/s]
Epoch: 73 | Loss: 0.05474821478128433
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.72it/s]
Epoch: 74 | Loss: 0.025466391816735268
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.75it/s]
Epoch: 75 | Loss: 0.0076312776654958725
100%|████████████████████████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.76it/s]
Epoch: 136 | Loss: 0.024680132046341896
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.73it/s]
Epoch: 137 | Loss: 0.00550298485904932
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.73it/s]
Epoch: 138 | Loss: 0.20077332854270935
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.78it/s]
Epoch: 139 | Loss: 0.08547922968864441
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.77it/s]
Epoch: 140 | Loss: 0.027913935482501984
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.76it/s]
Epoch: 141 | Loss: 0.09141761809587479
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.76it/s]
Epoch: 142 | Loss: 0.015537092462182045
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.78it/s]
Epoch: 143 | Loss: 0.10770005732774734
100%|████████████████████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.76it/s]
Epoch: 203 | Loss: 0.0014745454536750913
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.77it/s]
Epoch: 204 | Loss: 0.0005885128048248589
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.74it/s]
Epoch: 205 | Loss: 0.0004563160182442516
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.78it/s]
Epoch: 206 | Loss: 0.00037751602940261364
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.78it/s]
Epoch: 207 | Loss: 0.0003011666121892631
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.80it/s]
Epoch: 208 | Loss: 0.00030480261193588376
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.78it/s]
Epoch: 209 | Loss: 0.00022703275317326188
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.77it/s]
Epoch: 210 | Loss: 0.00023950228933244944
100%|███████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.76it/s]
Epoch: 270 | Loss: 0.0006448404164984822
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.81it/s]
Epoch: 271 | Loss: 0.0015178052708506584
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.77it/s]
Epoch: 272 | Loss: 0.0007093913736753166
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.81it/s]
Epoch: 273 | Loss: 0.00030546271591447294
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.77it/s]
Epoch: 274 | Loss: 0.0017760127084329724
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.78it/s]
Epoch: 275 | Loss: 0.0053202491253614426
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.84it/s]
Epoch: 276 | Loss: 0.00045027353917248547
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.73it/s]
Epoch: 277 | Loss: 0.0004257847904227674
100%|█████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 337 | Loss: 2.1114246919751167e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 338 | Loss: 2.7122874598717317e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 339 | Loss: 2.9164970328565687e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 340 | Loss: 2.3841617803554982e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 341 | Loss: 2.0775585653609596e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 342 | Loss: 2.053881689789705e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.86it/s]
Epoch: 343 | Loss: 1.7905678760143928e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 344 | Loss: 1.862685712694656e-05
100%|█████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.71it/s]
Epoch: 404 | Loss: 0.031432971358299255
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.70it/s]
Epoch: 405 | Loss: 0.003364417003467679
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.71it/s]
Epoch: 406 | Loss: 0.002081452403217554
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 407 | Loss: 0.024184346199035645
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.71it/s]
Epoch: 408 | Loss: 0.0020768430549651384
100%|███████████████████████████████████████████| 10/10 [00:06<00:00,  1.66it/s]
Epoch: 409 | Loss: 0.0025955913588404655
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
Epoch: 410 | Loss: 0.0006295299390330911
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.67it/s]
Epoch: 411 | Loss: 0.0056190816685557365
100%|███████████████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 471 | Loss: 2.9246431950014085e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.84it/s]
Epoch: 472 | Loss: 1.4220772754924837e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 473 | Loss: 2.0451681848498993e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 474 | Loss: 1.8347007426200435e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.83it/s]
Epoch: 475 | Loss: 2.099562516377773e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 476 | Loss: 1.834582508308813e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 477 | Loss: 2.257429514429532e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 478 | Loss: 1.810865978768561e-05
100%|███████████████

100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.81it/s]
Epoch: 538 | Loss: 2.474085704307072e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.82it/s]
Epoch: 539 | Loss: 1.957038330147043e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.81it/s]
Epoch: 540 | Loss: 3.226710396120325e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.81it/s]
Epoch: 541 | Loss: 2.3726572180748917e-05
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.83it/s]
Epoch: 542 | Loss: 0.0026330328546464443
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.83it/s]
Epoch: 543 | Loss: 0.00044973206240683794
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 544 | Loss: 0.08238127827644348
100%|███████████████████████████████████████████| 10/10 [00:05<00:00,  1.85it/s]
Epoch: 545 | Loss: 0.00021280103828758
100%|█████████████████████

In [4]:
!python main.py --data_path='/home/youngjoon/Desktop/Dataset/mocap_3djoints/' --n_epochs=100

Number of GPUs available: 1
Total Video Samples: 2514 || Total Participants: 77 || Train Participants: 62 || Validation Participants: 15
Train samples: 8415 || Validation samples: 4155
Evaluating mean and std for the training set...
/home/youngjoon/DEV/ntu-skeleton/code/dataset.py:396: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:204.)
  X = torch.tensor([self.read_sample(sample_name)[0] for sample_name in self.sample_set])
Mean and Std saved successfully!
Training...
  0%|                                                    | 0/17 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/youngjoon/DEV/ntu-skeleton/code/main.py", line 581, in <module>
    main(params)
  File "/home/youngjoon/DEV/ntu-skeleton/code/main.py", line 387, in main
    model = train(model, train_loa